name: snapshots

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering
  pull_request: # To test updates

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write # Needed to push tags and create releases
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetch all history for tags
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-node

      - name: Create artifacts file
        run: |
          ARTIFACT_PATHS_FILE=$(mktemp)
          echo "ARTIFACT_PATHS_FILE=$ARTIFACT_PATHS_FILE" >> $GITHUB_ENV

      - name: Build distribution files
        id: build-dist
        run: |
          pip install build
          python dev/build.py
          find $PWD/dist -type f -name "*.whl" >> $ARTIFACT_PATHS_FILE

      - name: Build Java distribution
        working-directory: mlflow/java
        run: |
          mvn -B -DskipTests clean package
          find $PWD -name "target" -type d \
            -exec find {} -name "*.jar" \
              ! -name "*sources.jar" \
              ! -name "*javadoc.jar" \
              ! -name "original-*.jar" \; >> $ARTIFACT_PATHS_FILE

      - name: Upload artifacts to nightly release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const script = require('./.github/scripts/snapshots.js');
            await script({
              github,
              context,
              artifactPathsFile: process.env.ARTIFACT_PATHS_FILE
            });
